name: quote_details
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1  
  flutter:
    sdk: flutter
  quote_repository:
    path: ../../quote_repository
  domain_models:
    path: ../../domain_models
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.1.4
  test: ^1.16.8
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true