name: monitoring
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_dynamic_links: ^6.0.11
  firebase_analytics: ^11.3.6
  firebase_remote_config: ^5.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8